name: flutter_application
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.3
  http: ^1.2.0
  flutter_secure_storage: ^9.2.4
  get: ^4.6.5
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  nepali_date_picker: ^6.0.2
  url_launcher: ^6.1.10
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0



flutter:

  
  uses-material-design: true
  assets:
    - assets/pregnancy_exercises.json
    - assets/pregnancy_nutrition.json

    

  