// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwgTRM_SaoyYrY4gSu24nJpDdNXJC7mss',
    appId: '1:685426197521:web:2284e8913cc2866af21db0',
    messagingSenderId: '685426197521',
    projectId: 'preg-frontend',
    authDomain: 'preg-frontend.firebaseapp.com',
    storageBucket: 'preg-frontend.firebasestorage.app',
    measurementId: 'G-FLBM599ZV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9xmP5_Jie_28jp352G86BQQ_57rVjYX4',
    appId: '1:685426197521:android:95074d319e94d931f21db0',
    messagingSenderId: '685426197521',
    projectId: 'preg-frontend',
    storageBucket: 'preg-frontend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjK7YZpaFqK6woEaEAMmJnkd5YB4STvJ8',
    appId: '1:685426197521:ios:67328d5f66938e0bf21db0',
    messagingSenderId: '685426197521',
    projectId: 'preg-frontend',
    storageBucket: 'preg-frontend.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjK7YZpaFqK6woEaEAMmJnkd5YB4STvJ8',
    appId: '1:685426197521:ios:67328d5f66938e0bf21db0',
    messagingSenderId: '685426197521',
    projectId: 'preg-frontend',
    storageBucket: 'preg-frontend.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwgTRM_SaoyYrY4gSu24nJpDdNXJC7mss',
    appId: '1:685426197521:web:ddecaf93246287baf21db0',
    messagingSenderId: '685426197521',
    projectId: 'preg-frontend',
    authDomain: 'preg-frontend.firebaseapp.com',
    storageBucket: 'preg-frontend.firebasestorage.app',
    measurementId: 'G-78BG7X57CC',
  );
}
